services:
  fountainflow-svc:
    image: quepugmer/fountainflow-svc:latest
    build: 
      context: .
      dockerfile: src/FountainFlow.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=FountainFlow;      
      - IdentityServiceUrl=http://fountainflow-svc
    ports:
      - 6087:80
    networks:
      - RallosZek-docker      
  ui:
    build:
      context: .
      dockerfile: src/FountainFlow.UI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80      
    ports:
      - "6266:80"
    networks:
      - RallosZek-docker            
volumes:
  pgdata:
networks:
  RallosZek-docker:
    external: true  